# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: lakshanrukantha
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: test-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: test-api

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
